#!/bin/bash
if [ $# -ne 1 ]
then
echo "Usage $0 <FileContainingList>"
exit
fi
java -classpath bin:jars/flickr4java-2.16.jar:jars/java-json.jar:jars/log4j.jar:jars/org-apache-commons-codec.jar:jars/scribe-1.3.2.jar:jars/scribejava-apis-2.5.2.jar com.mangalraj.Flicker.ModifyPhotos $1
